import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>박이슬 이력서</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          안녕하세요😎<br></br>풀스택 개발자 박이슬입니다.
          {/* <a href="https://nextjs.org">Next.js!</a> */}
        </h1>

        <p className={styles.description}>
          전세계 상용화 서비스를 만들자!
          {/* Get started by editing{" "} */}
          {/* <code className={styles.code}>pages/index.tsx</code> */}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Team project &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Personal project &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>

        <div>
          {/* 임시 */}
          <h5>[Frontend] HTML, CSS, typescript, Javascript</h5>
          <h5>[Backend] Java, Spring Boot, RESTful AP</h5>
          <h5>
            [AWS] AWS클라우드 환경 기반으로 팀프로젝트 진 (EC2, S3, RDS등)
          </h5>
        </div>
      </main>
      {/* ----------------- footer ----------------- */}
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          by ParkISeul😏
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
};

export default Home;
