import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// const Home: NextPage = () => {
const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>박이슬 이력서</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          안녕하세요😎<br></br>풀스택 개발자 박이슬입니다.
          {/* <a href="https://nextjs.org">Next.js!</a> */}
        </h1>

        <p className={styles.description}>
          전세계 상용화 서비스를 만들자!
          {/* Get started by editing{" "} */}
          {/* <code className={styles.code}>pages/index.tsx</code> */}
        </p>

        <div className={styles.grid0}>
          <a
            href="https://drive.google.com/file/d/1nBSR-PtIcW8HJTRWCmTLd-zE_JIGrpMx/view"
            className={styles.card0}
          >
            <h2>Portfolio &rarr;</h2>
            <p>
              <h5>
                이것은 박이슬의 포트폴리오다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                {/* <br />
                박이슬의-------------------------------------
                <br />
                포트폴리오 */}
              </h5>
            </p>
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href="http://ec2-3-34-181-87.ap-northeast-2.compute.amazonaws.com/"
            className={styles.card}
          >
            <h2>Team project &rarr;</h2>
            <p>
              <h5>
                AWS 클라우드 기반
                <br />
                회원과 강사 간의 유기적 연계를 제공하는
                <br />
                피트니스 예약 서비스 시스템
              </h5>
            </p>
          </a>

          <a href="./personal/personal" className={styles.card}>
            <h2>Personal project &rarr;</h2>
            <p>
              {" "}
              <h5>
                AWS 클라우드 기반
                <br />
                회원과 강사 간의 유기적 연계를 제공하는
                <br />
                피트니스 예약 서비스 시스템
              </h5>
            </p>
          </a>
        </div>

        {/*임시section */}
        <section className={styles.pr}>
          {/* pr-1 */}
          {/* <div
            className={styles.pr__container}
            // style="transform: translate(-44.9331%, 0%) translate3d(0px, 0px, 0px);"
          >
            <h2 className={styles.pr__title}>
              함께 일할 멋진 개발자를 찾고 계신가요? 😉
              <span className={styles.pr__title_accent}>
                개발자를&nbsp;
                <br className={styles.br_tablet} />
                찾고 계신가요?😉
              </span>
            </h2>
          </div>
           */}
          {/* pr-2 */}
          <div className={styles.pr__inner}>
            <div className={styles.feature}>
              {/* pr-2 left */}
              <strong className={styles.feature__title}>
                {/* 이럴 때 제가 딱<br />
                어울릴 것 같아요 */}
                저는 이런 사람이에요 👩🏻‍💼
              </strong>
              {/* pr-2 right */}
              <div className={styles.feature__content}>
                {/* <div className={styles.feature__block_1}> */}
                <div
                  className={styles.feature__content_1}
                  style={{ background: "#F2EEE5" }}
                >
                  ✍🏻 기술역량
                </div>
                {/* </div> */}
                <ul className={styles.feature__list}>
                  <li className={styles.feature__list_item}>
                    <strong>[Frontend]</strong> HTML, CSS, typescript,
                    Javascript
                  </li>
                  <li className={styles.feature__list_item}>
                    <strong>[Backend]</strong> Java, Spring Boot, RESTful AP
                  </li>
                  <li className={styles.feature__list_item}>
                    <strong>[AWS]</strong> AWS클라우드 환경 기반으로 팀프로젝트
                    진행 (EC2, S3, RDS등)
                  </li>
                </ul>
                <div
                  className={styles.feature__content_1}
                  style={{ background: "#E5C1C5" }}
                >
                  ✨ 나를 뽑아
                </div>
                {/* </div> */}
                <ul className={styles.feature__list}>
                  <li className={styles.feature__list_item}>
                    👀 역량과 경험을 갖춘 웹 퍼블리셔가 필요할 때
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 책임감 있고 함께 일할 때 시너지를 주는 팀원이 필요할 때
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 성장하지만 겸손을 잃지 않는 사람이 필요할 때
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 좋아하는 일을 잘하는 사람이 필요할 때
                  </li>
                </ul>
                <div
                  className={styles.feature__content_1}
                  style={{ background: "#C3E2DD" }}
                >
                  👑 저는
                </div>
                {/* </div> */}
                <ul className={styles.feature__list}>
                  <li className={styles.feature__list_item}>
                    👀 첫째, 작은 일이라도 처음부터 끝까지 맡는 책임감이 있는
                    사람
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 외주나 팀으로 일을 하게되면 책임을 지고 마무리 단계까지
                    잘 할것.
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 둘째, 변명하지 않는 사람
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 문제를 해결하고 빠르게 앞으로 나아갈 수 있는 해결책을
                    찾는 사람
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 마지막으로, 자신만의 원칙을 가진 사람
                  </li>
                  <li className={styles.feature__list_item}>
                    👀 자신 나름의 원칙과 기준이 있고, 그것을 고수해나갈 수 있는
                    분명한 사람 입니다.
                  </li>
                </ul>
                {/* ---------------------------------------------- */}
              </div>
            </div>
          </div>
        </section>
        {/* 임시끝 */}
      </main>
      {/* ----------------- footer ----------------- */}
      <footer className={styles.footer}>
        <a
          href="https://drive.google.com/file/d/1nBSR-PtIcW8HJTRWCmTLd-zE_JIGrpMx/view"
          target="_blank"
          rel="noopener noreferrer"
        >
          by ParkISeul😏
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  );
};

export default Home;
